services:

  dootask-site:
    image: ghcr.io/dootask/website/web:latest
    container_name: dootask-site
    ports:
      - "801:3000"
    volumes:
      - ./nginx/:/etc/nginx/conf.d/
    restart: unless-stopped