services:

  dootask-site:
    image: ghcr.io/dootask/website/web:latest
    container_name: dootask-site
    ports:
      - "8080:3000"
    environment:
      - NUXT_PRIVACY_REDIRECT_URL=${PRIVACY_REDIRECT_URL}
      - NUXT_PUBLIC_SITE_URL=${SITE_URL}
      - NUXT_PUBLIC_DEMO_URL=${DEMO_URL}
      - NUXT_PUBLIC_SAAS_URL=${SAAS_URL}
      - NUXT_PUBLIC_R2_PUBLIC_URL=${R2_PUBLIC_URL}
    restart: unless-stopped
